export const CATEGORY_LABELS: Record<string, string> = {
  'herramientas': 'Herramientas',
  'camping': 'Camping',
  'electronica': 'Electrónica',
  'deporte': 'Deporte',
  'hogar-jardin': 'Hogar y jardín',
  'fotografia-video': 'Fotografía y vídeo',
  'audio-musica': 'Audio y música',
  'transporte': 'Transporte',
  'bebe-ninos': 'Bebé y niños',
  'bricolaje-construccion': 'Bricolaje y construcción',
  'cocina-hosteleria': 'Cocina y hostelería',
  'ropa-moda': 'Ropa y moda',
  'juegos-consolas': 'Juegos y consolas',
  'libros-educacion': 'Libros y educación',
  'mascotas': 'Mascotas',
  'oficina-papeleria': 'Oficina y papelería',
  'otros': 'Otros',
};
